name: Sync OAS to ReadMe
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: readmeio/github-readme-sync@2.0.0
        with:
          readme-oas-key: ${{ secrets.README_OAS_KEY }}
          oas-file-path: './packages/api/src/schema/schema.json'
